name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    # if: github.actor == 'ehsanjso'
    # steps:
    #   - uses: hmarr/auto-approve-action@v4
    - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Renovate Approve Bot image
        run: docker pull ghcr.io/renovatebot/renovate-approve-bot:main
