name: Renovate
on:
  # This lets you dispatch a renovate job with different cache options if you want to reset or disable the cache manually.
  workflow_dispatch:
    inputs:
      repoCache:
        description: 'Reset or disable the cache?'
        type: choice
        default: enabled
        options:
          - enabled
          - disabled
          - reset
  schedule:
    # Run every 30 minutes:
    - cron: '0,59 * * * *'

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          private-key: ${{ secrets.private_key }}
          app-id: ${{ secrets.app_id }}
          owner: ${{ github.repository_owner }}
          repositories: 'ehsanjso/sample-monorepo-3'
      - name: Cache Node.js
        uses: actions/cache@v3
        with:
          path: /tmp/renovate/cache/renovate/
          key: node-cache-${{ runner.os }}-${{ hashFiles('.github/renovate-config.js') }}
          restore-keys: |
            node-cache-${{ runner.os }}-
      - uses: actions/checkout@v4

      - run: sudo chown -R 1000 /tmp/renovate

      - uses: renovatebot/github-action@v40.1.12
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-version: 37.414.1
        env:
          # This enables the cache -- if this is set, it's not necessary to add it to renovate.json.
          RENOVATE_REPOSITORY_CACHE: ${{ github.event.inputs.repoCache || 'enabled' }}

      - run: sudo chown -R $(whoami) /tmp/renovate
